### ISSUE TITLE
Support for VS Mac 2017

### ISSUE THREAD

**Issue by edencakir** [arjankuijpers/SpotifyRemote#12]
I'm not sure about whether that's possible, but that'd be awesome.

**Comment by arjankuijpers** [comment]
Im gonna look into it for you.

**Comment by edencakir** [comment]
@arjankuijpers thanks!

**Comment by arjankuijpers** [comment]
Although its would be cool to have SpotifyRemote working on Mac. It would be a whole different plugin none of the code would be shared, because Visual Studio 2017 for Mac isn't based on the Windows version. Meaning it's out of scope for this project. I may create a plugin for Visual Studio 2017 for Mac in the future. but it would be a different repository with different dependencies and different UI.
I hope this informs you to the full extend of your question.
